theme: jekyll-theme-minimal
title: "Needs in Intergroup Contact"
# description: "Author Information:<br>██████ ██████████<br>███████ ████████<br>█████ █████████<br>█████ ██ █████<br>███ ███████<br>████████████████████<br><br>[Authors and other identifying information removed for blind review.]"
description: "Jannis Kreienkamp<br>Maximilian Agostini<br>Laura F. Bringmann<br>Peter de Jonge<br>Kai Epstude<br>(University of Groningen)"
show_downloads: true
github: false